version: "3.9"
services:

  frontend:
    container_name: lab-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 7777:7777
    restart: on-failure
    networks:
      - network

  backend-1:
    container_name: lab-backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app:ro
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - MONGODB_URI=mongodb+srv://[...].mongodb.net/?retryWrites=true&w=majority
      - MONGODB_NAME=lab
    restart: on-failure
    networks:
      - network

  backend-2:
    container_name: lab-backend-2
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app:ro
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - MONGODB_URI=mongodb+srv://[...].mongodb.net/?retryWrites=true&w=majority
      - MONGODB_NAME=lab
    restart: on-failure
    networks:
      - network

  nginx:
    container_name: lab-nginx
    image: nginx:1.25.3-alpine
    ports:
      - 8000:8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-1
      - backend-2
    restart: on-failure
    networks:
      - network

networks:
  network:
